export const keysRU = {
    title: 'Название',
    name: 'Название',
    rotation_period: 'Период вращения',
    diameter: 'Диаметр',
    climate: 'Климат',
    gravity: 'Гравитация',
    terrain: 'Местность',
    surface_water: 'Покрытие водой',
    population: 'Население',
    eye_color: 'Цвет глаз',
    hair_color: 'Цвет волос',
    skin_color: 'Цвет кожи',
    birth_year: 'Дата рождения',
    gender: 'Пол',
    description: 'Описание',
    url: 'Cсылка',
    height: 'Рост',
    mass: 'Вес',
    episode_id: '№ эпизода',
    opening_crawl: 'Вводный текст',
    director: 'Режиссер',
    producer: 'Продюсер',
    release_date: 'Дата релиза',
    detail: 'Детали',
    orbital_period: 'Орбительный период',
    classification: 'Классификация',
    designation: 'Надвид',
    average_height: 'Средний рост',
    skin_colors: 'Цвет кожи',
    hair_colors: 'Цвет волос',
    model: 'Модель',
    manufacturer: 'Производитель',
    cost_in_credits: 'Стоимость',
    length: 'Длина',
    max_atmosphering_speed: 'Макс. скорость'
};